version: "2"
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.11-1.1.1
    ports:
      - "9092:9092"
    links:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${HOST_IP}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_CREATE_TOPICS: "deletingOrder:1:1,deletedOrder:1:1,updatingOrder:1:1,updatedOrder:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
# version: "2"
# services:
#   kafdrop:
#     image: obsidiandynamics/kafdrop
#     restart: "no"
#     ports:
#       - "9000:9000"
#     environment:
#       KAFKA_BROKERCONNECT: "kafka:29092"
#     depends_on:
#       - "kafka"
#   kafka:
#     image: obsidiandynamics/kafka
#     restart: "no"
#     ports:
#       - "2181:2181"
#       - "9092:9092"
#     environment:
#       # KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
#       # KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://localhost:9092"
#       # KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
#       # KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
#       # KAFKA_ZOOKEEPER_SESSION_TIMEOUT: "6000"
#       # KAFKA_RESTART_ATTEMPTS: "10"
#       # KAFKA_RESTART_DELAY: "5"
#       # ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: "0"
