import express from "express";
import swaggerUi from "swagger-ui-express";
import cors from "cors";

import { router } from "./routes";

import { swaggerDef } from "./swaggerDef";

const PORT = process.env.PORT || 8080;

// Create a instance of express services
const app = express();

// Adding middleware cores to express services
app.use(cors());

// Adding middleware to accept json at body requests and limiting 10kb
app.use(express.json({ limit: "10kb" }));

// Adding middleware to create routes to docs generated by swagger.
app.use("/docs", swaggerUi.serve, swaggerUi.setup(swaggerDef));

// Adding middleware to instance of all the routes.
app.use("/api/v1", router);

// Methods to start server.
const start = () => {
  try {
    // Method to make express service start to listen requests in port defined by const PORT.
    if (process.env.NODE_ENV !== "test")
      app.listen(PORT, () => {
        console.log(`Server started on port ${PORT}`);
        return;
      });
  } catch (error) {
    console.error(error);
    process.exit(1);
  }
};

start();

export { app };
