import express from "express";
import swaggerUi from "swagger-ui-express";
import cors from "cors";

import { router } from "./routes";

import swaggerDef from "./swagger-spec.json";
import { kafka } from "@libs/kafka";

const PORT = process.env.PORT || 8080;

// Create a instance of express services
const app = express();

// Adding middleware cores to express services
app.use(cors());

app.use((_, res, next) => {
  res.header("Access-Control-Allow-Origin", process.env.ORIGIN_URL); // Adjust as needed for CORS
  res.header(
    "Access-Control-Allow-Headers",
    "Origin, X-Requested-With, Content-Type, Accept, Authorization"
  );
  res.header("X-Content-Type-Options", "nosniff");
  res.header("X-Frame-Options", "DENY");
  res.header(
    "Strict-Transport-Security",
    "max-age=31536000; includeSubDomains"
  ); // Use HSTS
  res.header("X-XSS-Protection", "1; mode=block");
  next();
});

// Adding middleware to accept json at body requests and limiting 10kb
app.use(express.json({ limit: "10kb" }));

// Adding middleware to create routes to docs generated by swagger.
app.use("/docs", swaggerUi.serve, swaggerUi.setup(swaggerDef));

// Adding middleware to instance of all the routes.
app.use("/api/v1", router);

const kafkaAdmin = kafka.admin();

// Methods to start server.
const start = async () => {
  try {
    console.log(await kafkaAdmin.listTopics());
    // Method to make express service start to listen requests in port defined by const PORT.
    if (process.env.NODE_ENV !== "test")
      app.listen(PORT, () => {
        console.log(`API RUN IN: ${process.env.ORIGIN_URL}`);
      });
  } catch (error) {
    process.exit(1);
  }
};

start();

export { app };
